version: "3.4"

services:
  geo.api:
    image: geometry-application
    build:
      context: .
      dockerfile: Geo.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "88:80"
